// packages/piano-react/src/views/Main/components/ChordSelector.tsx
import React, { FC } from "react";
import { Chord } from "@stromland/piano-lib";
import { ToggleButton } from "components/ToggleButton/ToggleButton";

import styles from "./Selector.module.css";

interface ChordSelectorProps {
  chords: Chord[];
  selectedChord: Chord;
  handleSelectChord: (chord: Chord) => void;
}

export const ChordSelector: FC<ChordSelectorProps> = ({
  chords,
  handleSelectChord,
  selectedChord,
}) => {
  return (
    <div className={styles.container}>
      {chords.map((chord) => (
        <ChordButton
          key={chord.note}
          chord={chord}
          selectedChord={selectedChord}
          handleSelectChord={handleSelectChord}
        />
      ))}
    </div>
  );
};

interface ChordButtonProps {
  chord: Chord;
  handleSelectChord: (chord: Chord) => void;
  selectedChord: Chord;
}

const ChordButton: FC<ChordButtonProps> = ({
  chord,
  handleSelectChord,
  selectedChord,
}) => {
  const createChordName = (chord: Chord): string => chord.note + chord.suffix;
  const chordName = createChordName(chord);
  const selectedChordName = createChordName(selectedChord);

  return (
    <ToggleButton
      key={chordName}
      pressed={chordName === selectedChordName}
      onClick={() => handleSelectChord(chord)}
    >
      {chordName}
    </ToggleButton>
  );
};

// packages/piano-vue/src/components/ChordSelector/ChordSelector.vue
<script setup lang="ts">
import type { Chord } from '@stromland/piano-lib';
import { computed } from 'vue';

import ToggleButton from '../ToggleButton.vue';

type Props = {
  chords: Chord[];
  selected?: Chord;
  select: (chord: Chord) => void;
};

const props = defineProps<Props>();

const namedChords = computed(() => {
  return props.chords.reduce(
    (acc, chord) => {
      const name = getChordName(chord);
      if (name) {
        acc[name] = chord;
      }
      return acc;
    },
    {} as Record<string, Chord>,
  );
});

function getChordName(chord?: Chord): string | undefined {
  return chord && `${chord.note}${chord.suffix}`;
}
</script>

<template>
  <div class="chords-container">
    <ToggleButton
      v-for="(chord, name) in namedChords"
      :key="name"
      :pressed="name === getChordName(props.selected)"
      @click="props.select(chord)"
    >
      {{ name }}
    </ToggleButton>
  </div>
</template>

<style scoped>
.chords-container {
  display: flex;
}
</style>
