// packages/piano-vue/src/components/InversionSelector.vue
<script setup lang="ts">
import { Inversion } from '@stromland/piano-lib';

import ToggleButton from './ToggleButton.vue';

type Props = {
  select: (inversion: Inversion) => void;
  selected: Inversion;
};

const props = defineProps<Props>();
</script>

<template>
  <div class="inversion-container">
    <ToggleButton
      v-for="inversion in Inversion"
      :key="inversion"
      :pressed="props.selected === inversion"
      @click="props.select(inversion)"
    >
      {{ inversion }}
    </ToggleButton>
  </div>
</template>

<style scoped>
.inversion-container {
  display: flex;
}
</style>

// packages/piano-react/src/views/Main/components/InversionSelector.tsx
import React, { FC } from 'react';

import { ToggleButton } from 'components/ToggleButton/ToggleButton';
import { Inversion } from '@stromland/piano-lib';

import style from './Selector.module.css';

interface InversionSelectorProps {
  inversion: Inversion;
  handleSelectInversion: (inversion: Inversion) => void;
}

export const InversionSelector: FC<InversionSelectorProps> = ({
  inversion,
  handleSelectInversion,
}) => {
  return (
    <div className={style.container}>
      <ToggleButton
        pressed={inversion === Inversion.ROOT}
        onClick={() => handleSelectInversion(Inversion.ROOT)}
      >
        Root
      </ToggleButton>
      <ToggleButton
        pressed={inversion === Inversion.FIRST}
        onClick={() => handleSelectInversion(Inversion.FIRST)}
      >
        First
      </ToggleButton>
      <ToggleButton
        pressed={inversion === Inversion.SECOND}
        onClick={() => handleSelectInversion(Inversion.SECOND)}
      >
        Second
      </ToggleButton>
    </div>
  );
};
