// packages/piano-vue/src/components/ScaleSelector/NoteSelector.vue
<script setup lang="ts">
import { PIANO_NOTES, type Note } from '@stromland/piano-lib';
import ToggleButton from '../ToggleButton.vue';

type Props = {
  select: (note: Note) => void;
  selected: Note;
};

const props = defineProps<Props>();
</script>

<template>
  <div class="notes-container">
    <ToggleButton
      v-for="note in PIANO_NOTES"
      :key="note"
      :pressed="note === props.selected"
      @click="props.select(note)"
    >
      {{ note }}
    </ToggleButton>
  </div>
</template>

<style scoped>
.notes-container {
  display: flex;
}
</style>

// src/views/Main/components/NoteSelector.tsx
import React from "react";
import { PIANO_NOTES, Note } from "services/Piano";
import { ToggleButton } from "components/ToggleButton/ToggleButton";

import styles from "./Selector.module.css";

interface NoteSelectorProps {
  selectedNote: Note;
  handleSelectNote: (note: Note) => void;
}

export function NoteSelector({
  handleSelectNote,
  selectedNote
}: NoteSelectorProps) {
  return (
    <div className={styles.container}>
      {PIANO_NOTES.map(note => (
        <ToggleButton
          key={note}
          pressed={note === selectedNote}
          onClick={() => handleSelectNote(note)}
        >
          {note}
        </ToggleButton>
      ))}
    </div>
  );
}
