// packages/piano-react/src/views/Main/components/ScaleSelector.tsx
import React, { FC } from 'react';
import { ScaleType, Scale } from '@stromland/piano-lib';
import { ToggleButton } from 'components/ToggleButton/ToggleButton';

import style from './Selector.module.css';

interface ScaleSelectorProps {
  scale: ScaleType;
  handleSelectScale: (scale: ScaleType) => void;
}

export const ScaleSelector: FC<ScaleSelectorProps> = ({
  handleSelectScale,
  scale,
}) => {
  return (
    <div className={style.container}>
      {Object.keys(Scale.scales).map((key) => (
        <ToggleButton
          pressed={scale === key}
          onClick={() => handleSelectScale(key as ScaleType)}
        >
          {key}
        </ToggleButton>
      ))}
    </div>
  );
};

// packages/piano-vue/src/components/ScaleSelector/ScaleSelector.vue
<script setup lang="ts">
import ToggleButton from '../ToggleButton.vue';
import { Scale, type ScaleType } from '@stromland/piano-lib';

type Props = {
  select: (scale: ScaleType) => void;
  selected: ScaleType;
};

const props = defineProps<Props>();

const scaleNames: Record<ScaleType, string> = {
  major: 'Major',
  minor: 'Minor',
  harmonicMinor: 'Harmonic minor',
};
</script>

<template>
  <div class="scale-container">
    <ToggleButton
      v-for="(_, scale) in Scale.scales"
      :key="scale"
      :pressed="scale === props.selected"
      @click="props.select(scale)"
    >
      {{ scaleNames[scale] }}
    </ToggleButton>
  </div>
</template>

<style scoped>
.scale-container {
  display: flex;
}
</style>
