// packages/piano-react/src/components/PianoKeys/PianoKeys.tsx
import React, { FC } from 'react';
import classnames from 'classnames';

import { PianoKey } from '@stromland/piano-lib';

import './PianoKeys.css';

interface KeyProps {
  pianoKey: PianoKey;
}

const Key: FC<KeyProps> = ({ pianoKey }) => {
  const classes = classnames('key', {
    'black-key': pianoKey.black,
    pressed: pianoKey.pressed,
  });

  return (
    <div className={classes}>
      <span>{pianoKey.note}</span>
    </div>
  );
};

interface KeyGroupProps {
  keys: PianoKey[];
  pianoKey: PianoKey;
  keyIndex: number;
}

const KeyGroup: FC<KeyGroupProps> = ({ keys, pianoKey, keyIndex }) => {
  if (pianoKey.black) return null;
  const nextKey = keys.length > keyIndex + 1 ? keys[keyIndex + 1] : null;
  return (
    <div className="key-group">
      <Key pianoKey={pianoKey} />
      {nextKey && nextKey.black && <Key pianoKey={nextKey} />}
    </div>
  );
};

interface PianoKeysProps {
  keys: PianoKey[];
}

export const PianoKeys: FC<PianoKeysProps> = ({ keys }) => {
  return (
    <div className="key-container">
      {keys.map((key, index) => (
        <KeyGroup key={index} keys={keys} pianoKey={key} keyIndex={index} />
      ))}
    </div>
  );
};

// packages/piano-vue/src/components/PianoKeys/PianoKeys.vue
<script setup lang="ts">
import type { PianoKey } from '@stromland/piano-lib';
import PianoKeyGroup from './PianoKeyGroup.vue';

type Props = {
  keys: PianoKey[];
};

const props = defineProps<Props>();
</script>

<template>
  <div class="key-container">
    <PianoKeyGroup
      v-for="(key, index) in props.keys"
      :key="index"
      :keys="props.keys"
      :pianoKey="key"
      :keyIndex="index"
    />
  </div>
</template>

<style scoped>
.key-container {
  display: flex;
  height: 40%;
  max-height: 600px;
  position: relative;
  width: 100%;
}
</style>
